### PR TITLE
Update Manifest

### PR DESCRIPTION
**Pull request by nathakits**
add background color and start_url to the manifest

### CODE REVIEW

**Comment by willpatera** [comment]
@nathakits - why is the manifest located in `images/favicons/manifest.json`. Please make a new dir or put in an appropriate location.

**Comment by nathakits** [comment]
I was looking at pupil labs website manifest for reference and saw that the `manifest.json` is located in `content/images/favicons/manifest.json` and it's still is. So i thought i put it there the same. But i see it now. WIll move it to a new location.

**Comment by willpatera** [comment]
@nathakits please move the file to a better location as discussed and I can merge.

**Comment by willpatera** [comment]
@nathakits what is the status of this issue?

**Comment by nathakits** [comment]
Working on this issue right now

**Pull request closed without merging**
