### PR TITLE
Improve intrinsics estimation documentation

### PR DESCRIPTION
**Pull request by N-M-T**

### CODE REVIEW

**Review by papr — APPROVED** [review]
These changes are great! What do you think about linking the recorded narrow lens intrinsics with step-by-step instructions for using it?

**Comment by N-M-T** [comment]
@papr I thought about it. My concern is that the intrinsics estimation section is already quite dense, and that adding an additional option + instructions could lead to confusion.

**Comment by papr** [comment]
@N-M-T I agree that it is quite dense. What do you think about splitting it? I am thinking something like this:
1. High-level introduction into what intrinsic are and do in Pupil Core software
2. List of pre-recorded calibrations + link &intructions to narrow lens intrinsic
3. Explainer how to check if the selected intrinsic are correct (via undistorted image preview)
- move fov measurements into a dedicated section
- move custom estimation procedure to dev docs
- move notes on intrinsics persistency etc to dev docs

**Comment by N-M-T** [comment]
@papr I like your suggestions. The proposed structure is logical to me

**Comment by papr** [comment]
@N-M-T I would suggest merging this PR as it is and moving the proposed changes into a new PR. What do you think?

**Review by papr — APPROVED** [review]

**Pull request merged**
