### PR TITLE
Remove Pupil Mobile from docs

### PR DESCRIPTION
**Pull request by willpatera**
Pupil Mobile app is no longer actively maintained and Pupil Mobile bundles are no longer sold. Proposing to remove all docs for Pupil Mobile, so that new users don't get confused about "Pupil Mobile" 

@papr @mkassner I'd like your feedback on the following:
1. recording format for Pupil Mobile. I feel that technical docs for the recording format should be kept, but with a warning about the app no longer being maintained. Thoughts? 
2. **remote recorder** plugin docs have been removed in this PR. However,this plugin still exists in Capture. Do we also want to remove that plugin from Capture, or keep it and update the docs on it with depreciation warning?

### CODE REVIEW

**Comment by mkassner** [comment]
I would remove the PI mobile data format from the docs as well. I would keep the remote recorder plugin docs and add a deprecation warning.

**Comment by willpatera** [comment]
@mkassner I incorporated your suggestions. @papr any thoughts - please take a look.

**Comment by papr** [comment]
Given the internal discussion, I suggest moving user and recording format documentation to https://github.com/pupil-labs/pupil-mobile-app/ and referencing this repo from the `Remote Recorder` documentation. We can add a note that Pupil Mobile is no longer maintained.

We should also move the media files accordingly.

**Comment by mkassner** [comment]
@papr  sounds good. please go ahead and make a PR in that repo.

**Comment by papr** [comment]
PR for reference https://github.com/pupil-labs/pupil-mobile-app/pull/43

**Review by papr — APPROVED** [review]

**Pull request merged**
